name: Deploy

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Copy .env
        run: |
          cp .env.prod .env
          sed -i "s|{APP_KEY}|$APP_KEY|g" .env
          sed -i "s|{DB_USERNAME}|$DB_USERNAME|g" .env
          sed -i "s|{DB_PASSWORD}|$DB_PASSWORD|g" .env
          sed -i "s|{GOOGLE_APPLICATION_CREDENTIALS}|$GOOGLE_APPLICATION_CREDENTIALS|g" .env
          sed -i "s|{O4U_SECRET_KEY}|$O4U_SECRET_KEY|g" .env
          sed -i "s|{MOBILE_APP_KEY}|$MOBILE_APP_KEY|g" .env
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          O4U_SECRET_KEY: ${{ secrets.O4U_SECRET_KEY }}
          MOBILE_APP_KEY: ${{ secrets.MOBILE_APP_KEY }}

      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Frontend Assets
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          include-hidden-files: true
          path: |
            ${{ github.workspace }}
            !${{ github.workspace }}/.env
            !${{ github.workspace }}/.git
            !${{ github.workspace }}/.github

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}

      - name: Copy .env
        run: |
          cp .env.prod .env
          sed -i "s|{APP_KEY}|$APP_KEY|g" .env
          sed -i "s|{DB_USERNAME}|$DB_USERNAME|g" .env
          sed -i "s|{DB_PASSWORD}|$DB_PASSWORD|g" .env
          sed -i "s|{GOOGLE_APPLICATION_CREDENTIALS}|$GOOGLE_APPLICATION_CREDENTIALS|g" .env
          sed -i "s|{O4U_SECRET_KEY}|$O4U_SECRET_KEY|g" .env
          sed -i "s|{MOBILE_APP_KEY}|$MOBILE_APP_KEY|g" .env
          sed -i "s|{GOOGLE_CLIENT_ID}|$GOOGLE_CLIENT_ID|g" .env
          sed -i "s|{GOOGLE_CLIENT_SECRET}|$GOOGLE_CLIENT_SECRET|g" .env
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          O4U_SECRET_KEY: ${{ secrets.O4U_SECRET_KEY }}
          MOBILE_APP_KEY: ${{ secrets.MOBILE_APP_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      - name: Set up SSH private key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Configure SSH
        run: |
          touch ~/.ssh/config
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          touch ~/.ssh/known_hosts
          echo "$SSH_HOST $SSH_KEY" > ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Copy build to VPS
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ${{ github.workspace }}  ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/html/o4u
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/html/o4u/src
            mv /var/www/html/o4u/o4u /var/www/html/o4u/src
            cd /var/www/html/o4u/src
            rm -rf /var/www/html/o4u/src/storage/logs
            ln -s /var/www/html/o4u/logs/ /var/www/html/o4u/src/storage/
            php8.4 artisan migrate --force
            php8.4 artisan optimize:clear
            php8.4 artisan optimize
            chown -R www-data:www-data /var/www/html/o4u/src
            cp -f /var/www/html/o4u/src/deploy/supervisor/o4u-queue-worker.conf /etc/supervisor/conf.d/o4u-queue-worker.conf
            supervisorctl reread
            supervisorctl update
            supervisorctl restart "o4u-queue-worker:*"
